animal_teste = AnimalTeste()
animal_teste.create_animals()
animal_teste.make_sounds()

veterinario = Veterinario()
dog = Dog("Rex")
cat = Cat("Whiskers")
bird = Bird("Tweety")
veterinario.examinar(dog)
veterinario.examinar(cat)
veterinario.examinar(bird)

zoologico = Zoologico()
zoologico.add_animal(dog)
zoologico.add_animal(cat)
zoologico.add_animal(bird)
zoologico.make_sounds()
zoologico.make_animals_run()

produto_teste = ProdutoTeste()
mouse = Mouse("Loja A", 19.99, "Ótico, Saída USB. 1.600 dpi")
livro = Livro("Loja B", 29.99, "Autor X")
produto_teste.adicionar_produto(mouse)
produto_teste.adicionar_produto(livro)
produto_teste.exibir_descricoes()
